[book]
authors = ["John Philip"]
language = "en"
multilingual = false
src = "src"
title = "Rust Bytes Challenges"
description = "A collection of Rust Bytes weekly coding challenges"

[output.html]
default-theme = "rust"
preferred-dark-theme = "navy"
smart-punctuation = true
mathjax-support = false
copy-fonts = true
no-section-label = false
git-repository-url = "https://github.com/rust-bytes/weekly-challenges"
git-repository-icon = "fa-github"
edit-url-template = "https://github.com/rust-bytes/weekly-challenges/edit/main/guide/{path}"
site-url = "/weekly-challenges/"
cname = "weekly-challenges.rs"
input-404 = "not-found.md"

[output.html.playground]
editable = true        # allows editing the source code
copyable = true          # include the copy button for copying code snippets
copy-js = true           # includes the JavaScript for the code editor
line-numbers = true     # displays line numbers for editable code
runnable = true          # displays a run button for rust code


[output.epub]
title = "Rust Bytes Challenges (EPUB)"
author = "John Philip"
optional = true

[output.pdf]
title = "Rust_Bytes_Challenges_(PDF)"
author = "John Philip"

[output.html.print]
enable = true

[output.html.search]
limit-results = 15
